/** Default storefront home configuration (single-document seed). */
export const defaultFrontHomeSettings = {
    theme: {
        primaryColor: "#019ee3",
        secondaryColor: "#afcb09",
        headerGradientFrom: "#0c115d",
        headerGradientTo: "#1a237e",
        homeBackgroundFrom: "#e6fbff",
        homeBackgroundTo: "#f7fafd",
    },
    logo: {
        url: "",
        useTextLogo: true,
        textPrimary: "corp",
        textAccent: "culture",
    },
    banner: {
        slides: [],
        mobileHeight: 250,
        desktopHeight: 480,
        autoplaySpeed: 3000,
        accentColor: "#019ee3",
    },
    navTabs: [
        { id: "home", label: "Home", path: "/", visible: true, muted: false },
        { id: "products", label: "Products", path: "/products", visible: true, muted: false },
    ],
    offerCategories: [
        {
            id: "rental",
            category: "Rental",
            description: "Equipment and asset rental solutions for your business.",
            discount: "25% OFF",
            image: "https://images.pexels.com/photos/5834/nature-grass-leaf-green.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            themeColor: "#059669",
            visible: true,
            order: 0,
        },
        {
            id: "credit",
            category: "Credit",
            description: "Flexible credit options for registered company customers.",
            discount: "25% OFF",
            image: "https://images.pexels.com/photos/3747139/pexels-photo-3747139.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            themeColor: "#7c3aed",
            visible: true,
            order: 1,
        },
        {
            id: "amc",
            category: "AMC / AMLC",
            description: "Annual maintenance contracts for printers, AC, and IT assets.",
            discount: "25% OFF",
            image: "https://images.pexels.com/photos/5834/nature-grass-leaf-green.jpg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
            themeColor: "#0284c7",
            visible: true,
            order: 2,
        },
    ],
    services: [
        { id: "1", title: "AC Service", iconKey: "AirVent", bgColor: "from-red-300 to-red-500", description: "Professional AC installation, repair and maintenance services", visible: true, order: 0 },
        { id: "2", title: "Printer Service", iconKey: "Printer", bgColor: "from-fuchsia-300 to-fuchsia-500", description: "Expert printer repair, maintenance and troubleshooting", visible: true, order: 1 },
        { id: "3", title: "Toner & Cartridge", iconKey: "BookOpen", bgColor: "from-amber-300 to-amber-500", description: "Quality toner and cartridge refill for all printer models", visible: true, order: 2 },
        { id: "4", title: "Waterproof & Paint", iconKey: "PaintBucket", bgColor: "from-lime-300 to-lime-500", description: "Professional waterproofing and painting solutions", visible: true, order: 3 },
        { id: "5", title: "Mobile Service", iconKey: "Smartphone", bgColor: "from-cyan-300 to-cyan-500", description: "Complete mobile repair and maintenance services", visible: true, order: 4 },
        { id: "6", title: "Computer Service", iconKey: "Monitor", bgColor: "from-purple-300 to-purple-500", description: "Comprehensive computer repair and support services", visible: true, order: 5 },
        { id: "7", title: "CCTV/Camera Fixing", iconKey: "Camera", bgColor: "from-violet-300 to-violet-500", description: "Professional CCTV installation and maintenance services", visible: true, order: 6 },
    ],
    homeProducts: [
        { id: "1", title: "Foods", bgColor: "from-red-400 to-red-600", status: "COMING SOON", image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800", visible: true, order: 0, categorySlug: "" },
        { id: "2", title: "Events Management", bgColor: "from-purple-400 to-purple-600", status: "COMING SOON", image: "https://images.pexels.com/photos/2747449/pexels-photo-2747449.jpeg?auto=compress&cs=tinysrgb&w=800", visible: true, order: 1, categorySlug: "" },
        { id: "3", title: "Printer & Toner", bgColor: "from-lime-400 to-lime-600", status: "COMING SOON", image: "https://images.pexels.com/photos/3843284/pexels-photo-3843284.jpeg?auto=compress&cs=tinysrgb&w=800", visible: true, order: 2, categorySlug: "" },
        { id: "4", title: "CCTV Camera Fixing", bgColor: "from-violet-400 to-violet-600", status: "COMING SOON", image: "https://images.pexels.com/photos/430208/pexels-photo-430208.jpeg?auto=compress&cs=tinysrgb&w=800", visible: true, order: 3, categorySlug: "" },
        { id: "5", title: "Computer Service", bgColor: "from-blue-400 to-blue-600", status: "COMING SOON", image: "https://images.pexels.com/photos/1779487/pexels-photo-1779487.jpeg?auto=compress&cs=tinysrgb&w=800", visible: true, order: 4, categorySlug: "" },
        { id: "6", title: "Stationery", bgColor: "from-gray-400 to-gray-600", status: "COMING SOON", image: "https://images.pexels.com/photos/6446709/pexels-photo-6446709.jpeg?auto=compress&cs=tinysrgb&w=800", visible: true, order: 5, categorySlug: "" },
    ],
    categoryBanners: [],
    serviceDefaultImage: "",
    rentalDefaultImage: "",
    sales: {
        assuredBadgeLabel: "Corpculture Assured",
        showAssuredBadge: true,
        creditOptionEnabled: true,
        creditLabel: "Pay on Company Credit",
    },
    service: {
        creditOptionEnabled: true,
        creditLabel: "Request service on credit",
    },
    categorySearch: {
        enabled: true,
        placeholder: "Search categories...",
        showOnHome: true,
    },
};
